name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          set -ex
          sudo apt update
          sudo apt install xorriso grub-pc-bin grub-efi mtools make python3 dosfstools e2fsprogs squashfs-tools python3-yaml gcc wget curl unzip xz-utils debootstrap git erofs-utils zstd
          git clone https://gitlab.com/tearch-linux/applications-and-tools/teaiso
          cd teaiso
          sudo make && sudo make install
          cd ..
          pwd
          sudo mkteaiso -p /home/runner/work/teaiso-profile/teaiso-profile
          sudo mkdir -p /output
          sudo mv /var/teaiso/output/*.iso /output/puffos-daily.iso


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "main"
          prerelease: false
          title: "Daily build"
          files: |
            /output/*

